### ISSUE TITLE
Can not install pgspecial against psycopg2-binary

### ISSUE THREAD

**Issue by ratijas** [dbcli/pgspecial#156]
Trying to follow the guide at https://jupysql.ploomber.io/en/latest/howto/postgres-install.html#installing-pgspecial

It recommends installing `psycopg2-binary` because why  compiling from sources when it's already done? But then it recommends `install "pgspecial<2"` — which doesn't work because apparently `psycopg2-binary` doesn't "provide" `psycopg2` in terms of Python's dependency management.

What's the way out of this dll hell?

**Comment by ratijas** [comment]
For now I solved this with the following terrible hack.

_/pyproject.toml_
```toml
[project]
name = "my-project"
version = "0.1"
requires-python = ">=3.13"
dependencies = [
    "psycopg2-binary",
    "psycopg2",
    "pgspecial<2",
]

[tool.uv.sources]
psycopg2 = { path = "./dummy-psycopg2" }
```

_/dummy-psycopg2/pyproject.toml:_
```toml
[project]
name = "psycopg2"
version = "2.9.10"
requires-python = ">=3.13"
dependencies = [
]
```

Basically, I created a fake empty package to override uv/pip/PyPi package resolution.
